# Generated by Django 4.1.3 on 2022-11-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_servicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicing',
            name='date',
            field=models.DateField(verbose_name='Servicing Date'),
        ),
    ]
