# Generated by Django 4.1.3 on 2022-11-07 22:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_mod_alter_servicing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
